<?php
/**
 * ClusterEncryption
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;

use \ArrayAccess;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * ClusterEncryption Class Doc Comment
 *
 * @category Class
 * @description The cluster&#39;s encryption state. Read-only, in full.  Every field here is written by the encryption action service or by the restart recheck; none of them is writable through any serializer, which is what keeps &#x60;&#x60;start_encryption_operation&#x60;&#x60; the only write path.  PUBLISHED WHETHER OR NOT &#x60;&#x60;K8S_ENCRYPTION_ENABLED&#x60;&#x60; IS SET, and that is not an oversight -- the spec requires it, so that the global gate \&quot;cannot strand an &#x60;unknown&#x60; cluster\&quot;: the read, an already-queued operation and the staff reconcile recovery all stay reachable while the feature is dark, and only the ordinary toggle POST answers 404. So this is the one flag whose only call site is &#x60;&#x60;set_encryption&#x60;&#x60;.  It also makes the API and the panel disagree about what a disabled feature exposes: &#x60;&#x60;cluster_fe.views.encryption_context&#x60;&#x60; returns None while the flag is off and the detail page drops the whole card. That difference is PUSH against PULL. The panel would put a red \&quot;State unknown\&quot; badge in front of every customer who opened their cluster page, for a feature they have not been told about; a caller who requested this resource by name asked the question, and answering it honestly is not advertising. Read either side&#39;s reason and the other one is half the argument -- they are one decision.
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClusterEncryption implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ClusterEncryption';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'mode' => 'string',
        'status' => '\PidginHost\Sdk\Model\ClusterEncryptionStatusEnum',
        'changed_at' => 'string',
        'verified_at' => 'string',
        'restart_required' => 'bool',
        'restart_required_at' => 'string',
        'restart_checked_at' => 'string',
        'stale_pod_count' => 'int',
        'reason' => 'string',
        'error' => 'string',
        'per_node' => 'array<string,mixed>',
        'operation' => '\PidginHost\Sdk\Model\ClusterEncryptionOperation'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'mode' => null,
        'status' => null,
        'changed_at' => null,
        'verified_at' => null,
        'restart_required' => null,
        'restart_required_at' => null,
        'restart_checked_at' => null,
        'stale_pod_count' => null,
        'reason' => null,
        'error' => null,
        'per_node' => null,
        'operation' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'mode' => false,
        'status' => false,
        'changed_at' => true,
        'verified_at' => true,
        'restart_required' => false,
        'restart_required_at' => true,
        'restart_checked_at' => true,
        'stale_pod_count' => true,
        'reason' => false,
        'error' => false,
        'per_node' => false,
        'operation' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'mode' => 'mode',
        'status' => 'status',
        'changed_at' => 'changed_at',
        'verified_at' => 'verified_at',
        'restart_required' => 'restart_required',
        'restart_required_at' => 'restart_required_at',
        'restart_checked_at' => 'restart_checked_at',
        'stale_pod_count' => 'stale_pod_count',
        'reason' => 'reason',
        'error' => 'error',
        'per_node' => 'per_node',
        'operation' => 'operation'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'mode' => 'setMode',
        'status' => 'setStatus',
        'changed_at' => 'setChangedAt',
        'verified_at' => 'setVerifiedAt',
        'restart_required' => 'setRestartRequired',
        'restart_required_at' => 'setRestartRequiredAt',
        'restart_checked_at' => 'setRestartCheckedAt',
        'stale_pod_count' => 'setStalePodCount',
        'reason' => 'setReason',
        'error' => 'setError',
        'per_node' => 'setPerNode',
        'operation' => 'setOperation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'mode' => 'getMode',
        'status' => 'getStatus',
        'changed_at' => 'getChangedAt',
        'verified_at' => 'getVerifiedAt',
        'restart_required' => 'getRestartRequired',
        'restart_required_at' => 'getRestartRequiredAt',
        'restart_checked_at' => 'getRestartCheckedAt',
        'stale_pod_count' => 'getStalePodCount',
        'reason' => 'getReason',
        'error' => 'getError',
        'per_node' => 'getPerNode',
        'operation' => 'getOperation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const REASON_FEATURE_UNAVAILABLE = 'feature_unavailable';
    public const REASON_CLUSTER_OPERATION_IN_PROGRESS = 'cluster_operation_in_progress';
    public const REASON_RESOURCE_NOT_ACTIVE = 'resource_not_active';
    public const REASON_CLUSTER_NOT_PROVISIONED = 'cluster_not_provisioned';
    public const REASON_INVALID_ENCRYPTION_MODE = 'invalid_encryption_mode';
    public const REASON_WORKLOAD_RESTART_ACK_REQUIRED = 'workload_restart_ack_required';
    public const REASON_ENCRYPTION_STATE_UNKNOWN = 'encryption_state_unknown';
    public const REASON_ENCRYPTION_ALREADY_IN_REQUESTED_MODE = 'encryption_already_in_requested_mode';
    public const REASON_RECONCILE_REQUIRES_STAFF = 'reconcile_requires_staff';
    public const REASON_RECONCILE_REQUIRES_UNKNOWN_STATE = 'reconcile_requires_unknown_state';
    public const REASON_CILIUM_VERSION_MISMATCH = 'cilium_version_mismatch';
    public const REASON_KERNEL_WIREGUARD_UNAVAILABLE = 'kernel_wireguard_unavailable';
    public const REASON_KERNEL_NODES_UNKNOWN = 'kernel_nodes_unknown';
    public const REASON_HELM_UPGRADE_FAILED = 'helm_upgrade_failed';
    public const REASON_HELM_ROLLBACK_FAILED = 'helm_rollback_failed';
    public const REASON_CILIUM_ROLLOUT_FAILED = 'cilium_rollout_failed';
    public const REASON_CILIUM_NODE_KEY_MISSING = 'cilium_node_key_missing';
    public const REASON_CILIUM_PEER_VERIFICATION_FAILED = 'cilium_peer_verification_failed';
    public const REASON_CILIUM_AGENT_UNREADABLE = 'cilium_agent_unreadable';
    public const REASON_CILIUM_AGENT_STATE_MISMATCH = 'cilium_agent_state_mismatch';
    public const REASON_CILIUM_ENCRYPTION_NOT_ACTIVE = 'cilium_encryption_not_active';
    public const REASON_CILIUM_ENCRYPTION_STILL_ACTIVE = 'cilium_encryption_still_active';
    public const REASON_CILIUM_NODES_UNKNOWN = 'cilium_nodes_unknown';
    public const REASON_CILIUM_MODE_UNSUPPORTED = 'cilium_mode_unsupported';
    public const REASON_CILIUM_VERIFICATION_MISCONFIGURED = 'cilium_verification_misconfigured';
    public const REASON_RESTART_RECHECK_FAILED = 'restart_recheck_failed';
    public const REASON_PLATFORM_RESTART_INCOMPLETE = 'platform_restart_incomplete';
    public const REASON_ENCRYPTION_TASK_ABORTED = 'encryption_task_aborted';
    public const REASON_DISPATCH_PENDING = 'dispatch_pending';
    public const REASON_EMPTY = '';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReasonAllowableValues()
    {
        return [
            self::REASON_FEATURE_UNAVAILABLE,
            self::REASON_CLUSTER_OPERATION_IN_PROGRESS,
            self::REASON_RESOURCE_NOT_ACTIVE,
            self::REASON_CLUSTER_NOT_PROVISIONED,
            self::REASON_INVALID_ENCRYPTION_MODE,
            self::REASON_WORKLOAD_RESTART_ACK_REQUIRED,
            self::REASON_ENCRYPTION_STATE_UNKNOWN,
            self::REASON_ENCRYPTION_ALREADY_IN_REQUESTED_MODE,
            self::REASON_RECONCILE_REQUIRES_STAFF,
            self::REASON_RECONCILE_REQUIRES_UNKNOWN_STATE,
            self::REASON_CILIUM_VERSION_MISMATCH,
            self::REASON_KERNEL_WIREGUARD_UNAVAILABLE,
            self::REASON_KERNEL_NODES_UNKNOWN,
            self::REASON_HELM_UPGRADE_FAILED,
            self::REASON_HELM_ROLLBACK_FAILED,
            self::REASON_CILIUM_ROLLOUT_FAILED,
            self::REASON_CILIUM_NODE_KEY_MISSING,
            self::REASON_CILIUM_PEER_VERIFICATION_FAILED,
            self::REASON_CILIUM_AGENT_UNREADABLE,
            self::REASON_CILIUM_AGENT_STATE_MISMATCH,
            self::REASON_CILIUM_ENCRYPTION_NOT_ACTIVE,
            self::REASON_CILIUM_ENCRYPTION_STILL_ACTIVE,
            self::REASON_CILIUM_NODES_UNKNOWN,
            self::REASON_CILIUM_MODE_UNSUPPORTED,
            self::REASON_CILIUM_VERIFICATION_MISCONFIGURED,
            self::REASON_RESTART_RECHECK_FAILED,
            self::REASON_PLATFORM_RESTART_INCOMPLETE,
            self::REASON_ENCRYPTION_TASK_ABORTED,
            self::REASON_DISPATCH_PENDING,
            self::REASON_EMPTY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('changed_at', $data ?? [], null);
        $this->setIfExists('verified_at', $data ?? [], null);
        $this->setIfExists('restart_required', $data ?? [], null);
        $this->setIfExists('restart_required_at', $data ?? [], null);
        $this->setIfExists('restart_checked_at', $data ?? [], null);
        $this->setIfExists('stale_pod_count', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
        $this->setIfExists('per_node', $data ?? [], null);
        $this->setIfExists('operation', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['mode'] === null) {
            $invalidProperties[] = "'mode' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['changed_at'] === null && !$this->isNullableSetToNull('changed_at')) {
            $invalidProperties[] = "'changed_at' is required";
        }
        if ($this->container['verified_at'] === null && !$this->isNullableSetToNull('verified_at')) {
            $invalidProperties[] = "'verified_at' is required";
        }
        if ($this->container['restart_required'] === null) {
            $invalidProperties[] = "'restart_required' can't be null";
        }
        if ($this->container['restart_required_at'] === null && !$this->isNullableSetToNull('restart_required_at')) {
            $invalidProperties[] = "'restart_required_at' is required";
        }
        if ($this->container['restart_checked_at'] === null && !$this->isNullableSetToNull('restart_checked_at')) {
            $invalidProperties[] = "'restart_checked_at' is required";
        }
        if ($this->container['stale_pod_count'] === null && !$this->isNullableSetToNull('stale_pod_count')) {
            $invalidProperties[] = "'stale_pod_count' is required";
        }
        if ($this->container['reason'] === null) {
            $invalidProperties[] = "'reason' can't be null";
        }
        $allowedValues = $this->getReasonAllowableValues();
        if (!is_null($this->container['reason']) && !in_array($this->container['reason'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reason', must be one of '%s'",
                $this->container['reason'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['error'] === null) {
            $invalidProperties[] = "'error' can't be null";
        }
        if ($this->container['per_node'] === null) {
            $invalidProperties[] = "'per_node' can't be null";
        }
        if ($this->container['operation'] === null && !$this->isNullableSetToNull('operation')) {
            $invalidProperties[] = "'operation' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets mode
     *
     * @return string
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string $mode mode
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \PidginHost\Sdk\Model\ClusterEncryptionStatusEnum
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \PidginHost\Sdk\Model\ClusterEncryptionStatusEnum $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets changed_at
     *
     * @return string|null
     */
    public function getChangedAt()
    {
        return $this->container['changed_at'];
    }

    /**
     * Sets changed_at
     *
     * @param string|null $changed_at changed_at
     *
     * @return self
     */
    public function setChangedAt($changed_at)
    {
        if (is_null($changed_at)) {
            array_push($this->openAPINullablesSetToNull, 'changed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('changed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['changed_at'] = $changed_at;

        return $this;
    }

    /**
     * Gets verified_at
     *
     * @return string|null
     */
    public function getVerifiedAt()
    {
        return $this->container['verified_at'];
    }

    /**
     * Sets verified_at
     *
     * @param string|null $verified_at verified_at
     *
     * @return self
     */
    public function setVerifiedAt($verified_at)
    {
        if (is_null($verified_at)) {
            array_push($this->openAPINullablesSetToNull, 'verified_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('verified_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['verified_at'] = $verified_at;

        return $this;
    }

    /**
     * Gets restart_required
     *
     * @return bool
     */
    public function getRestartRequired()
    {
        return $this->container['restart_required'];
    }

    /**
     * Sets restart_required
     *
     * @param bool $restart_required restart_required
     *
     * @return self
     */
    public function setRestartRequired($restart_required)
    {
        if (is_null($restart_required)) {
            throw new \InvalidArgumentException('non-nullable restart_required cannot be null');
        }
        $this->container['restart_required'] = $restart_required;

        return $this;
    }

    /**
     * Gets restart_required_at
     *
     * @return string|null
     */
    public function getRestartRequiredAt()
    {
        return $this->container['restart_required_at'];
    }

    /**
     * Sets restart_required_at
     *
     * @param string|null $restart_required_at restart_required_at
     *
     * @return self
     */
    public function setRestartRequiredAt($restart_required_at)
    {
        if (is_null($restart_required_at)) {
            array_push($this->openAPINullablesSetToNull, 'restart_required_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('restart_required_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['restart_required_at'] = $restart_required_at;

        return $this;
    }

    /**
     * Gets restart_checked_at
     *
     * @return string|null
     */
    public function getRestartCheckedAt()
    {
        return $this->container['restart_checked_at'];
    }

    /**
     * Sets restart_checked_at
     *
     * @param string|null $restart_checked_at restart_checked_at
     *
     * @return self
     */
    public function setRestartCheckedAt($restart_checked_at)
    {
        if (is_null($restart_checked_at)) {
            array_push($this->openAPINullablesSetToNull, 'restart_checked_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('restart_checked_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['restart_checked_at'] = $restart_checked_at;

        return $this;
    }

    /**
     * Gets stale_pod_count
     *
     * @return int|null
     */
    public function getStalePodCount()
    {
        return $this->container['stale_pod_count'];
    }

    /**
     * Sets stale_pod_count
     *
     * @param int|null $stale_pod_count stale_pod_count
     *
     * @return self
     */
    public function setStalePodCount($stale_pod_count)
    {
        if (is_null($stale_pod_count)) {
            array_push($this->openAPINullablesSetToNull, 'stale_pod_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('stale_pod_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['stale_pod_count'] = $stale_pod_count;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string $reason reason
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $allowedValues = $this->getReasonAllowableValues();
        if (!in_array($reason, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'reason', must be one of '%s'",
                    $reason,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string $error error
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets per_node
     *
     * @return array<string,mixed>
     */
    public function getPerNode()
    {
        return $this->container['per_node'];
    }

    /**
     * Sets per_node
     *
     * @param array<string,mixed> $per_node Evidence from the NEWEST operation, which may not have any yet.  A freshly queued operation carries an empty ``verification_result``, so this blanks the moment a toggle is admitted while ``mode`` and ``status`` still describe the last verified state. An empty map therefore means \"no evidence from the current operation\", NEVER \"verification failed\" -- read ``operation.status`` to tell them apart. Showing the previous operation's rows instead would label evidence for one mode as evidence for another.
     *
     * @return self
     */
    public function setPerNode($per_node)
    {
        if (is_null($per_node)) {
            throw new \InvalidArgumentException('non-nullable per_node cannot be null');
        }
        $this->container['per_node'] = $per_node;

        return $this;
    }

    /**
     * Gets operation
     *
     * @return \PidginHost\Sdk\Model\ClusterEncryptionOperation|null
     */
    public function getOperation()
    {
        return $this->container['operation'];
    }

    /**
     * Sets operation
     *
     * @param \PidginHost\Sdk\Model\ClusterEncryptionOperation|null $operation operation
     *
     * @return self
     */
    public function setOperation($operation)
    {
        if (is_null($operation)) {
            array_push($this->openAPINullablesSetToNull, 'operation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('operation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['operation'] = $operation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


