<?php
/**
 * DepositStatusEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\\Sdk\Model;
use \PidginHost\\Sdk\ObjectSerializer;

/**
 * DepositStatusEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;unpaid&#x60; - Unpaid * &#x60;paid&#x60; - Paid * &#x60;processing&#x60; - Processing * &#x60;invalid&#x60; - Invalid
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DepositStatusEnum
{
    /**
     * Possible values of this enum
     */
    public const UNPAID = 'unpaid';

    public const PAID = 'paid';

    public const PROCESSING = 'processing';

    public const INVALID = 'invalid';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNPAID,
            self::PAID,
            self::PROCESSING,
            self::INVALID
        ];
    }
}


