<?php
/**
 * DNSRecordCreateTypeEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\\Sdk\Model;
use \PidginHost\\Sdk\ObjectSerializer;

/**
 * DNSRecordCreateTypeEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;A&#x60; - A * &#x60;AAAA&#x60; - AAAA * &#x60;TYPE257&#x60; - TYPE257 * &#x60;CNAME&#x60; - CNAME * &#x60;MX&#x60; - MX * &#x60;SRV&#x60; - SRV * &#x60;TXT&#x60; - TXT
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DNSRecordCreateTypeEnum
{
    /**
     * Possible values of this enum
     */
    public const A = 'A';

    public const AAAA = 'AAAA';

    public const TYPE257 = 'TYPE257';

    public const CNAME = 'CNAME';

    public const MX = 'MX';

    public const SRV = 'SRV';

    public const TXT = 'TXT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::A,
            self::AAAA,
            self::TYPE257,
            self::CNAME,
            self::MX,
            self::SRV,
            self::TXT
        ];
    }
}


