<?php
/**
 * DnsSourceEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * DnsSourceEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;manual&#x60; - Manual * &#x60;freedns_internal&#x60; - FreeDNS (registered) * &#x60;freedns_external&#x60; - FreeDNS (external)
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DnsSourceEnum
{
    /**
     * Possible values of this enum
     */
    public const MANUAL = 'manual';

    public const FREEDNS_INTERNAL = 'freedns_internal';

    public const FREEDNS_EXTERNAL = 'freedns_external';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MANUAL,
            self::FREEDNS_INTERNAL,
            self::FREEDNS_EXTERNAL
        ];
    }
}


