<?php
/**
 * FwPolicyOutEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\\Sdk\Model;
use \PidginHost\\Sdk\ObjectSerializer;

/**
 * FwPolicyOutEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;ACCEPT&#x60; - ACCEPT * &#x60;DROP&#x60; - DROP * &#x60;REJECT&#x60; - REJECT
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FwPolicyOutEnum
{
    /**
     * Possible values of this enum
     */
    public const ACCEPT = 'ACCEPT';

    public const DROP = 'DROP';

    public const REJECT = 'REJECT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACCEPT,
            self::DROP,
            self::REJECT
        ];
    }
}


