<?php
/**
 * KubeVersionEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * KubeVersionEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;1.33.11&#x60; - 1.33.11 * &#x60;1.34.7&#x60; - 1.34.7 * &#x60;1.35.4&#x60; - 1.35.4
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KubeVersionEnum
{
    /**
     * Possible values of this enum
     */
    public const _1_33_11 = '1.33.11';

    public const _1_34_7 = '1.34.7';

    public const _1_35_4 = '1.35.4';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_1_33_11,
            self::_1_34_7,
            self::_1_35_4
        ];
    }
}


