<?php
/**
 * NodeOperationRetryRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;

use \ArrayAccess;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * NodeOperationRetryRequest Class Doc Comment
 *
 * @category Class
 * @description The two independent overrides, and the acknowledgement each one needs.  Both flags are tri-state and the third state is what matters: &#x60;null&#x60;/absent means \&quot;leave it as it is\&quot;. A plain boolean default would turn every request that names one flag into a request that silently un-forces the other, and &#x60;retry_node_operation&#x60; refuses an un-force rather than applying it.
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NodeOperationRetryRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'NodeOperationRetryRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'bypass_pdb' => 'bool',
        'delete_unmanaged_pods' => 'bool',
        'acknowledge_pdb_bypass' => 'bool',
        'acknowledge_unmanaged_pod_deletion' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'bypass_pdb' => null,
        'delete_unmanaged_pods' => null,
        'acknowledge_pdb_bypass' => null,
        'acknowledge_unmanaged_pod_deletion' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'bypass_pdb' => true,
        'delete_unmanaged_pods' => true,
        'acknowledge_pdb_bypass' => false,
        'acknowledge_unmanaged_pod_deletion' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bypass_pdb' => 'bypass_pdb',
        'delete_unmanaged_pods' => 'delete_unmanaged_pods',
        'acknowledge_pdb_bypass' => 'acknowledge_pdb_bypass',
        'acknowledge_unmanaged_pod_deletion' => 'acknowledge_unmanaged_pod_deletion'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bypass_pdb' => 'setBypassPdb',
        'delete_unmanaged_pods' => 'setDeleteUnmanagedPods',
        'acknowledge_pdb_bypass' => 'setAcknowledgePdbBypass',
        'acknowledge_unmanaged_pod_deletion' => 'setAcknowledgeUnmanagedPodDeletion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bypass_pdb' => 'getBypassPdb',
        'delete_unmanaged_pods' => 'getDeleteUnmanagedPods',
        'acknowledge_pdb_bypass' => 'getAcknowledgePdbBypass',
        'acknowledge_unmanaged_pod_deletion' => 'getAcknowledgeUnmanagedPodDeletion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('bypass_pdb', $data ?? [], null);
        $this->setIfExists('delete_unmanaged_pods', $data ?? [], null);
        $this->setIfExists('acknowledge_pdb_bypass', $data ?? [], false);
        $this->setIfExists('acknowledge_unmanaged_pod_deletion', $data ?? [], false);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bypass_pdb
     *
     * @return bool|null
     */
    public function getBypassPdb()
    {
        return $this->container['bypass_pdb'];
    }

    /**
     * Sets bypass_pdb
     *
     * @param bool|null $bypass_pdb bypass_pdb
     *
     * @return self
     */
    public function setBypassPdb($bypass_pdb)
    {
        if (is_null($bypass_pdb)) {
            array_push($this->openAPINullablesSetToNull, 'bypass_pdb');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bypass_pdb', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bypass_pdb'] = $bypass_pdb;

        return $this;
    }

    /**
     * Gets delete_unmanaged_pods
     *
     * @return bool|null
     */
    public function getDeleteUnmanagedPods()
    {
        return $this->container['delete_unmanaged_pods'];
    }

    /**
     * Sets delete_unmanaged_pods
     *
     * @param bool|null $delete_unmanaged_pods delete_unmanaged_pods
     *
     * @return self
     */
    public function setDeleteUnmanagedPods($delete_unmanaged_pods)
    {
        if (is_null($delete_unmanaged_pods)) {
            array_push($this->openAPINullablesSetToNull, 'delete_unmanaged_pods');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delete_unmanaged_pods', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delete_unmanaged_pods'] = $delete_unmanaged_pods;

        return $this;
    }

    /**
     * Gets acknowledge_pdb_bypass
     *
     * @return bool|null
     */
    public function getAcknowledgePdbBypass()
    {
        return $this->container['acknowledge_pdb_bypass'];
    }

    /**
     * Sets acknowledge_pdb_bypass
     *
     * @param bool|null $acknowledge_pdb_bypass acknowledge_pdb_bypass
     *
     * @return self
     */
    public function setAcknowledgePdbBypass($acknowledge_pdb_bypass)
    {
        if (is_null($acknowledge_pdb_bypass)) {
            throw new \InvalidArgumentException('non-nullable acknowledge_pdb_bypass cannot be null');
        }
        $this->container['acknowledge_pdb_bypass'] = $acknowledge_pdb_bypass;

        return $this;
    }

    /**
     * Gets acknowledge_unmanaged_pod_deletion
     *
     * @return bool|null
     */
    public function getAcknowledgeUnmanagedPodDeletion()
    {
        return $this->container['acknowledge_unmanaged_pod_deletion'];
    }

    /**
     * Sets acknowledge_unmanaged_pod_deletion
     *
     * @param bool|null $acknowledge_unmanaged_pod_deletion acknowledge_unmanaged_pod_deletion
     *
     * @return self
     */
    public function setAcknowledgeUnmanagedPodDeletion($acknowledge_unmanaged_pod_deletion)
    {
        if (is_null($acknowledge_unmanaged_pod_deletion)) {
            throw new \InvalidArgumentException('non-nullable acknowledge_unmanaged_pod_deletion cannot be null');
        }
        $this->container['acknowledge_unmanaged_pod_deletion'] = $acknowledge_unmanaged_pod_deletion;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


