<?php
/**
 * PatchedClusterDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;

use \ArrayAccess;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * PatchedClusterDetail Class Doc Comment
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PatchedClusterDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PatchedClusterDetail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'status' => '\PidginHost\Sdk\Model\StatusA57Enum',
        'name' => 'string',
        'generation' => 'string',
        'cluster_type' => 'string',
        'kube_version' => 'string',
        'price_per_month' => 'float',
        'price_per_hour' => 'string',
        'features' => '\PidginHost\Sdk\Model\FeaturesEnum[]',
        'features_ready' => 'bool',
        'kubeconfig_valid_until' => 'string',
        'ipv4_address' => 'string',
        'ipv6_address' => 'string',
        'dual_stack' => 'string',
        'protected' => 'bool',
        'talos_version' => 'string',
        'talos_upgrade_available' => 'string',
        'talos_next_version' => 'string',
        'storage_quota_gb' => 'string',
        'last_pool_used_bytes' => 'string',
        'last_storage_sync_at' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'status' => null,
        'name' => null,
        'generation' => null,
        'cluster_type' => null,
        'kube_version' => null,
        'price_per_month' => 'decimal',
        'price_per_hour' => null,
        'features' => null,
        'features_ready' => null,
        'kubeconfig_valid_until' => null,
        'ipv4_address' => null,
        'ipv6_address' => null,
        'dual_stack' => null,
        'protected' => null,
        'talos_version' => null,
        'talos_upgrade_available' => null,
        'talos_next_version' => null,
        'storage_quota_gb' => null,
        'last_pool_used_bytes' => null,
        'last_storage_sync_at' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'status' => false,
        'name' => false,
        'generation' => false,
        'cluster_type' => false,
        'kube_version' => false,
        'price_per_month' => false,
        'price_per_hour' => false,
        'features' => false,
        'features_ready' => false,
        'kubeconfig_valid_until' => false,
        'ipv4_address' => false,
        'ipv6_address' => false,
        'dual_stack' => false,
        'protected' => false,
        'talos_version' => false,
        'talos_upgrade_available' => false,
        'talos_next_version' => false,
        'storage_quota_gb' => false,
        'last_pool_used_bytes' => false,
        'last_storage_sync_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'status' => 'status',
        'name' => 'name',
        'generation' => 'generation',
        'cluster_type' => 'cluster_type',
        'kube_version' => 'kube_version',
        'price_per_month' => 'price_per_month',
        'price_per_hour' => 'price_per_hour',
        'features' => 'features',
        'features_ready' => 'features_ready',
        'kubeconfig_valid_until' => 'kubeconfig_valid_until',
        'ipv4_address' => 'ipv4_address',
        'ipv6_address' => 'ipv6_address',
        'dual_stack' => 'dual_stack',
        'protected' => 'protected',
        'talos_version' => 'talos_version',
        'talos_upgrade_available' => 'talos_upgrade_available',
        'talos_next_version' => 'talos_next_version',
        'storage_quota_gb' => 'storage_quota_gb',
        'last_pool_used_bytes' => 'last_pool_used_bytes',
        'last_storage_sync_at' => 'last_storage_sync_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'status' => 'setStatus',
        'name' => 'setName',
        'generation' => 'setGeneration',
        'cluster_type' => 'setClusterType',
        'kube_version' => 'setKubeVersion',
        'price_per_month' => 'setPricePerMonth',
        'price_per_hour' => 'setPricePerHour',
        'features' => 'setFeatures',
        'features_ready' => 'setFeaturesReady',
        'kubeconfig_valid_until' => 'setKubeconfigValidUntil',
        'ipv4_address' => 'setIpv4Address',
        'ipv6_address' => 'setIpv6Address',
        'dual_stack' => 'setDualStack',
        'protected' => 'setProtected',
        'talos_version' => 'setTalosVersion',
        'talos_upgrade_available' => 'setTalosUpgradeAvailable',
        'talos_next_version' => 'setTalosNextVersion',
        'storage_quota_gb' => 'setStorageQuotaGb',
        'last_pool_used_bytes' => 'setLastPoolUsedBytes',
        'last_storage_sync_at' => 'setLastStorageSyncAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'status' => 'getStatus',
        'name' => 'getName',
        'generation' => 'getGeneration',
        'cluster_type' => 'getClusterType',
        'kube_version' => 'getKubeVersion',
        'price_per_month' => 'getPricePerMonth',
        'price_per_hour' => 'getPricePerHour',
        'features' => 'getFeatures',
        'features_ready' => 'getFeaturesReady',
        'kubeconfig_valid_until' => 'getKubeconfigValidUntil',
        'ipv4_address' => 'getIpv4Address',
        'ipv6_address' => 'getIpv6Address',
        'dual_stack' => 'getDualStack',
        'protected' => 'getProtected',
        'talos_version' => 'getTalosVersion',
        'talos_upgrade_available' => 'getTalosUpgradeAvailable',
        'talos_next_version' => 'getTalosNextVersion',
        'storage_quota_gb' => 'getStorageQuotaGb',
        'last_pool_used_bytes' => 'getLastPoolUsedBytes',
        'last_storage_sync_at' => 'getLastStorageSyncAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('generation', $data ?? [], null);
        $this->setIfExists('cluster_type', $data ?? [], null);
        $this->setIfExists('kube_version', $data ?? [], null);
        $this->setIfExists('price_per_month', $data ?? [], null);
        $this->setIfExists('price_per_hour', $data ?? [], null);
        $this->setIfExists('features', $data ?? [], null);
        $this->setIfExists('features_ready', $data ?? [], null);
        $this->setIfExists('kubeconfig_valid_until', $data ?? [], null);
        $this->setIfExists('ipv4_address', $data ?? [], null);
        $this->setIfExists('ipv6_address', $data ?? [], null);
        $this->setIfExists('dual_stack', $data ?? [], null);
        $this->setIfExists('protected', $data ?? [], null);
        $this->setIfExists('talos_version', $data ?? [], null);
        $this->setIfExists('talos_upgrade_available', $data ?? [], null);
        $this->setIfExists('talos_next_version', $data ?? [], null);
        $this->setIfExists('storage_quota_gb', $data ?? [], null);
        $this->setIfExists('last_pool_used_bytes', $data ?? [], null);
        $this->setIfExists('last_storage_sync_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 200)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['price_per_month']) && !preg_match("/^-?\\d{0,16}(?:\\.\\d{0,4})?$/", $this->container['price_per_month'])) {
            $invalidProperties[] = "invalid value for 'price_per_month', must be conform to the pattern /^-?\\d{0,16}(?:\\.\\d{0,4})?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \PidginHost\Sdk\Model\StatusA57Enum|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \PidginHost\Sdk\Model\StatusA57Enum|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 200)) {
            throw new \InvalidArgumentException('invalid length for $name when calling PatchedClusterDetail., must be smaller than or equal to 200.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets generation
     *
     * @return string|null
     */
    public function getGeneration()
    {
        return $this->container['generation'];
    }

    /**
     * Sets generation
     *
     * @param string|null $generation generation
     *
     * @return self
     */
    public function setGeneration($generation)
    {
        if (is_null($generation)) {
            throw new \InvalidArgumentException('non-nullable generation cannot be null');
        }
        $this->container['generation'] = $generation;

        return $this;
    }

    /**
     * Gets cluster_type
     *
     * @return string|null
     */
    public function getClusterType()
    {
        return $this->container['cluster_type'];
    }

    /**
     * Sets cluster_type
     *
     * @param string|null $cluster_type cluster_type
     *
     * @return self
     */
    public function setClusterType($cluster_type)
    {
        if (is_null($cluster_type)) {
            throw new \InvalidArgumentException('non-nullable cluster_type cannot be null');
        }
        $this->container['cluster_type'] = $cluster_type;

        return $this;
    }

    /**
     * Gets kube_version
     *
     * @return string|null
     */
    public function getKubeVersion()
    {
        return $this->container['kube_version'];
    }

    /**
     * Sets kube_version
     *
     * @param string|null $kube_version kube_version
     *
     * @return self
     */
    public function setKubeVersion($kube_version)
    {
        if (is_null($kube_version)) {
            throw new \InvalidArgumentException('non-nullable kube_version cannot be null');
        }
        $this->container['kube_version'] = $kube_version;

        return $this;
    }

    /**
     * Gets price_per_month
     *
     * @return float|null
     */
    public function getPricePerMonth()
    {
        return $this->container['price_per_month'];
    }

    /**
     * Sets price_per_month
     *
     * @param float|null $price_per_month price_per_month
     *
     * @return self
     */
    public function setPricePerMonth($price_per_month)
    {
        if (is_null($price_per_month)) {
            throw new \InvalidArgumentException('non-nullable price_per_month cannot be null');
        }

        if ((!preg_match("/^-?\\d{0,16}(?:\\.\\d{0,4})?$/", ObjectSerializer::toString($price_per_month)))) {
            throw new \InvalidArgumentException("invalid value for \$price_per_month when calling PatchedClusterDetail., must conform to the pattern /^-?\\d{0,16}(?:\\.\\d{0,4})?$/.");
        }

        $this->container['price_per_month'] = $price_per_month;

        return $this;
    }

    /**
     * Gets price_per_hour
     *
     * @return string|null
     */
    public function getPricePerHour()
    {
        return $this->container['price_per_hour'];
    }

    /**
     * Sets price_per_hour
     *
     * @param string|null $price_per_hour price_per_hour
     *
     * @return self
     */
    public function setPricePerHour($price_per_hour)
    {
        if (is_null($price_per_hour)) {
            throw new \InvalidArgumentException('non-nullable price_per_hour cannot be null');
        }
        $this->container['price_per_hour'] = $price_per_hour;

        return $this;
    }

    /**
     * Gets features
     *
     * @return \PidginHost\Sdk\Model\FeaturesEnum[]|null
     */
    public function getFeatures()
    {
        return $this->container['features'];
    }

    /**
     * Sets features
     *
     * @param \PidginHost\Sdk\Model\FeaturesEnum[]|null $features features
     *
     * @return self
     */
    public function setFeatures($features)
    {
        if (is_null($features)) {
            throw new \InvalidArgumentException('non-nullable features cannot be null');
        }
        $this->container['features'] = $features;

        return $this;
    }

    /**
     * Gets features_ready
     *
     * @return bool|null
     */
    public function getFeaturesReady()
    {
        return $this->container['features_ready'];
    }

    /**
     * Sets features_ready
     *
     * @param bool|null $features_ready features_ready
     *
     * @return self
     */
    public function setFeaturesReady($features_ready)
    {
        if (is_null($features_ready)) {
            throw new \InvalidArgumentException('non-nullable features_ready cannot be null');
        }
        $this->container['features_ready'] = $features_ready;

        return $this;
    }

    /**
     * Gets kubeconfig_valid_until
     *
     * @return string|null
     */
    public function getKubeconfigValidUntil()
    {
        return $this->container['kubeconfig_valid_until'];
    }

    /**
     * Sets kubeconfig_valid_until
     *
     * @param string|null $kubeconfig_valid_until kubeconfig_valid_until
     *
     * @return self
     */
    public function setKubeconfigValidUntil($kubeconfig_valid_until)
    {
        if (is_null($kubeconfig_valid_until)) {
            throw new \InvalidArgumentException('non-nullable kubeconfig_valid_until cannot be null');
        }
        $this->container['kubeconfig_valid_until'] = $kubeconfig_valid_until;

        return $this;
    }

    /**
     * Gets ipv4_address
     *
     * @return string|null
     */
    public function getIpv4Address()
    {
        return $this->container['ipv4_address'];
    }

    /**
     * Sets ipv4_address
     *
     * @param string|null $ipv4_address ipv4_address
     *
     * @return self
     */
    public function setIpv4Address($ipv4_address)
    {
        if (is_null($ipv4_address)) {
            throw new \InvalidArgumentException('non-nullable ipv4_address cannot be null');
        }
        $this->container['ipv4_address'] = $ipv4_address;

        return $this;
    }

    /**
     * Gets ipv6_address
     *
     * @return string|null
     */
    public function getIpv6Address()
    {
        return $this->container['ipv6_address'];
    }

    /**
     * Sets ipv6_address
     *
     * @param string|null $ipv6_address ipv6_address
     *
     * @return self
     */
    public function setIpv6Address($ipv6_address)
    {
        if (is_null($ipv6_address)) {
            throw new \InvalidArgumentException('non-nullable ipv6_address cannot be null');
        }
        $this->container['ipv6_address'] = $ipv6_address;

        return $this;
    }

    /**
     * Gets dual_stack
     *
     * @return string|null
     */
    public function getDualStack()
    {
        return $this->container['dual_stack'];
    }

    /**
     * Sets dual_stack
     *
     * @param string|null $dual_stack dual_stack
     *
     * @return self
     */
    public function setDualStack($dual_stack)
    {
        if (is_null($dual_stack)) {
            throw new \InvalidArgumentException('non-nullable dual_stack cannot be null');
        }
        $this->container['dual_stack'] = $dual_stack;

        return $this;
    }

    /**
     * Gets protected
     *
     * @return bool|null
     */
    public function getProtected()
    {
        return $this->container['protected'];
    }

    /**
     * Sets protected
     *
     * @param bool|null $protected protected
     *
     * @return self
     */
    public function setProtected($protected)
    {
        if (is_null($protected)) {
            throw new \InvalidArgumentException('non-nullable protected cannot be null');
        }
        $this->container['protected'] = $protected;

        return $this;
    }

    /**
     * Gets talos_version
     *
     * @return string|null
     */
    public function getTalosVersion()
    {
        return $this->container['talos_version'];
    }

    /**
     * Sets talos_version
     *
     * @param string|null $talos_version talos_version
     *
     * @return self
     */
    public function setTalosVersion($talos_version)
    {
        if (is_null($talos_version)) {
            throw new \InvalidArgumentException('non-nullable talos_version cannot be null');
        }
        $this->container['talos_version'] = $talos_version;

        return $this;
    }

    /**
     * Gets talos_upgrade_available
     *
     * @return string|null
     */
    public function getTalosUpgradeAvailable()
    {
        return $this->container['talos_upgrade_available'];
    }

    /**
     * Sets talos_upgrade_available
     *
     * @param string|null $talos_upgrade_available talos_upgrade_available
     *
     * @return self
     */
    public function setTalosUpgradeAvailable($talos_upgrade_available)
    {
        if (is_null($talos_upgrade_available)) {
            throw new \InvalidArgumentException('non-nullable talos_upgrade_available cannot be null');
        }
        $this->container['talos_upgrade_available'] = $talos_upgrade_available;

        return $this;
    }

    /**
     * Gets talos_next_version
     *
     * @return string|null
     */
    public function getTalosNextVersion()
    {
        return $this->container['talos_next_version'];
    }

    /**
     * Sets talos_next_version
     *
     * @param string|null $talos_next_version talos_next_version
     *
     * @return self
     */
    public function setTalosNextVersion($talos_next_version)
    {
        if (is_null($talos_next_version)) {
            throw new \InvalidArgumentException('non-nullable talos_next_version cannot be null');
        }
        $this->container['talos_next_version'] = $talos_next_version;

        return $this;
    }

    /**
     * Gets storage_quota_gb
     *
     * @return string|null
     */
    public function getStorageQuotaGb()
    {
        return $this->container['storage_quota_gb'];
    }

    /**
     * Sets storage_quota_gb
     *
     * @param string|null $storage_quota_gb storage_quota_gb
     *
     * @return self
     */
    public function setStorageQuotaGb($storage_quota_gb)
    {
        if (is_null($storage_quota_gb)) {
            throw new \InvalidArgumentException('non-nullable storage_quota_gb cannot be null');
        }
        $this->container['storage_quota_gb'] = $storage_quota_gb;

        return $this;
    }

    /**
     * Gets last_pool_used_bytes
     *
     * @return string|null
     */
    public function getLastPoolUsedBytes()
    {
        return $this->container['last_pool_used_bytes'];
    }

    /**
     * Sets last_pool_used_bytes
     *
     * @param string|null $last_pool_used_bytes last_pool_used_bytes
     *
     * @return self
     */
    public function setLastPoolUsedBytes($last_pool_used_bytes)
    {
        if (is_null($last_pool_used_bytes)) {
            throw new \InvalidArgumentException('non-nullable last_pool_used_bytes cannot be null');
        }
        $this->container['last_pool_used_bytes'] = $last_pool_used_bytes;

        return $this;
    }

    /**
     * Gets last_storage_sync_at
     *
     * @return string|null
     */
    public function getLastStorageSyncAt()
    {
        return $this->container['last_storage_sync_at'];
    }

    /**
     * Sets last_storage_sync_at
     *
     * @param string|null $last_storage_sync_at last_storage_sync_at
     *
     * @return self
     */
    public function setLastStorageSyncAt($last_storage_sync_at)
    {
        if (is_null($last_storage_sync_at)) {
            throw new \InvalidArgumentException('non-nullable last_storage_sync_at cannot be null');
        }
        $this->container['last_storage_sync_at'] = $last_storage_sync_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


