<?php
/**
 * PoolRemovalItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;

use \ArrayAccess;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * PoolRemovalItem Class Doc Comment
 *
 * @category Class
 * @description One worker a journal is removing, and how far its removal got.
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PoolRemovalItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PoolRemovalItem';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'target_hostname' => 'string',
        'cordoned_at' => 'string',
        'drained_at' => 'string',
        'detached_at' => 'string',
        'validated_at' => 'string',
        'reset_started_at' => 'string',
        'reset_completed_at' => 'string',
        'node_deleted_at' => 'string',
        'vm_deleted_at' => 'string',
        'uncordoned_at' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'target_hostname' => null,
        'cordoned_at' => null,
        'drained_at' => null,
        'detached_at' => null,
        'validated_at' => null,
        'reset_started_at' => null,
        'reset_completed_at' => null,
        'node_deleted_at' => null,
        'vm_deleted_at' => null,
        'uncordoned_at' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'target_hostname' => false,
        'cordoned_at' => true,
        'drained_at' => true,
        'detached_at' => true,
        'validated_at' => true,
        'reset_started_at' => true,
        'reset_completed_at' => true,
        'node_deleted_at' => true,
        'vm_deleted_at' => true,
        'uncordoned_at' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'target_hostname' => 'target_hostname',
        'cordoned_at' => 'cordoned_at',
        'drained_at' => 'drained_at',
        'detached_at' => 'detached_at',
        'validated_at' => 'validated_at',
        'reset_started_at' => 'reset_started_at',
        'reset_completed_at' => 'reset_completed_at',
        'node_deleted_at' => 'node_deleted_at',
        'vm_deleted_at' => 'vm_deleted_at',
        'uncordoned_at' => 'uncordoned_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'target_hostname' => 'setTargetHostname',
        'cordoned_at' => 'setCordonedAt',
        'drained_at' => 'setDrainedAt',
        'detached_at' => 'setDetachedAt',
        'validated_at' => 'setValidatedAt',
        'reset_started_at' => 'setResetStartedAt',
        'reset_completed_at' => 'setResetCompletedAt',
        'node_deleted_at' => 'setNodeDeletedAt',
        'vm_deleted_at' => 'setVmDeletedAt',
        'uncordoned_at' => 'setUncordonedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'target_hostname' => 'getTargetHostname',
        'cordoned_at' => 'getCordonedAt',
        'drained_at' => 'getDrainedAt',
        'detached_at' => 'getDetachedAt',
        'validated_at' => 'getValidatedAt',
        'reset_started_at' => 'getResetStartedAt',
        'reset_completed_at' => 'getResetCompletedAt',
        'node_deleted_at' => 'getNodeDeletedAt',
        'vm_deleted_at' => 'getVmDeletedAt',
        'uncordoned_at' => 'getUncordonedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('target_hostname', $data ?? [], null);
        $this->setIfExists('cordoned_at', $data ?? [], null);
        $this->setIfExists('drained_at', $data ?? [], null);
        $this->setIfExists('detached_at', $data ?? [], null);
        $this->setIfExists('validated_at', $data ?? [], null);
        $this->setIfExists('reset_started_at', $data ?? [], null);
        $this->setIfExists('reset_completed_at', $data ?? [], null);
        $this->setIfExists('node_deleted_at', $data ?? [], null);
        $this->setIfExists('vm_deleted_at', $data ?? [], null);
        $this->setIfExists('uncordoned_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['target_hostname'] === null) {
            $invalidProperties[] = "'target_hostname' can't be null";
        }
        if ($this->container['cordoned_at'] === null && !$this->isNullableSetToNull('cordoned_at')) {
            $invalidProperties[] = "'cordoned_at' is required";
        }
        if ($this->container['drained_at'] === null && !$this->isNullableSetToNull('drained_at')) {
            $invalidProperties[] = "'drained_at' is required";
        }
        if ($this->container['detached_at'] === null && !$this->isNullableSetToNull('detached_at')) {
            $invalidProperties[] = "'detached_at' is required";
        }
        if ($this->container['validated_at'] === null && !$this->isNullableSetToNull('validated_at')) {
            $invalidProperties[] = "'validated_at' is required";
        }
        if ($this->container['reset_started_at'] === null && !$this->isNullableSetToNull('reset_started_at')) {
            $invalidProperties[] = "'reset_started_at' is required";
        }
        if ($this->container['reset_completed_at'] === null && !$this->isNullableSetToNull('reset_completed_at')) {
            $invalidProperties[] = "'reset_completed_at' is required";
        }
        if ($this->container['node_deleted_at'] === null && !$this->isNullableSetToNull('node_deleted_at')) {
            $invalidProperties[] = "'node_deleted_at' is required";
        }
        if ($this->container['vm_deleted_at'] === null && !$this->isNullableSetToNull('vm_deleted_at')) {
            $invalidProperties[] = "'vm_deleted_at' is required";
        }
        if ($this->container['uncordoned_at'] === null && !$this->isNullableSetToNull('uncordoned_at')) {
            $invalidProperties[] = "'uncordoned_at' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets target_hostname
     *
     * @return string
     */
    public function getTargetHostname()
    {
        return $this->container['target_hostname'];
    }

    /**
     * Sets target_hostname
     *
     * @param string $target_hostname target_hostname
     *
     * @return self
     */
    public function setTargetHostname($target_hostname)
    {
        if (is_null($target_hostname)) {
            throw new \InvalidArgumentException('non-nullable target_hostname cannot be null');
        }
        $this->container['target_hostname'] = $target_hostname;

        return $this;
    }

    /**
     * Gets cordoned_at
     *
     * @return string|null
     */
    public function getCordonedAt()
    {
        return $this->container['cordoned_at'];
    }

    /**
     * Sets cordoned_at
     *
     * @param string|null $cordoned_at cordoned_at
     *
     * @return self
     */
    public function setCordonedAt($cordoned_at)
    {
        if (is_null($cordoned_at)) {
            array_push($this->openAPINullablesSetToNull, 'cordoned_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cordoned_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cordoned_at'] = $cordoned_at;

        return $this;
    }

    /**
     * Gets drained_at
     *
     * @return string|null
     */
    public function getDrainedAt()
    {
        return $this->container['drained_at'];
    }

    /**
     * Sets drained_at
     *
     * @param string|null $drained_at drained_at
     *
     * @return self
     */
    public function setDrainedAt($drained_at)
    {
        if (is_null($drained_at)) {
            array_push($this->openAPINullablesSetToNull, 'drained_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('drained_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['drained_at'] = $drained_at;

        return $this;
    }

    /**
     * Gets detached_at
     *
     * @return string|null
     */
    public function getDetachedAt()
    {
        return $this->container['detached_at'];
    }

    /**
     * Sets detached_at
     *
     * @param string|null $detached_at detached_at
     *
     * @return self
     */
    public function setDetachedAt($detached_at)
    {
        if (is_null($detached_at)) {
            array_push($this->openAPINullablesSetToNull, 'detached_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('detached_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['detached_at'] = $detached_at;

        return $this;
    }

    /**
     * Gets validated_at
     *
     * @return string|null
     */
    public function getValidatedAt()
    {
        return $this->container['validated_at'];
    }

    /**
     * Sets validated_at
     *
     * @param string|null $validated_at validated_at
     *
     * @return self
     */
    public function setValidatedAt($validated_at)
    {
        if (is_null($validated_at)) {
            array_push($this->openAPINullablesSetToNull, 'validated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validated_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validated_at'] = $validated_at;

        return $this;
    }

    /**
     * Gets reset_started_at
     *
     * @return string|null
     */
    public function getResetStartedAt()
    {
        return $this->container['reset_started_at'];
    }

    /**
     * Sets reset_started_at
     *
     * @param string|null $reset_started_at reset_started_at
     *
     * @return self
     */
    public function setResetStartedAt($reset_started_at)
    {
        if (is_null($reset_started_at)) {
            array_push($this->openAPINullablesSetToNull, 'reset_started_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reset_started_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reset_started_at'] = $reset_started_at;

        return $this;
    }

    /**
     * Gets reset_completed_at
     *
     * @return string|null
     */
    public function getResetCompletedAt()
    {
        return $this->container['reset_completed_at'];
    }

    /**
     * Sets reset_completed_at
     *
     * @param string|null $reset_completed_at reset_completed_at
     *
     * @return self
     */
    public function setResetCompletedAt($reset_completed_at)
    {
        if (is_null($reset_completed_at)) {
            array_push($this->openAPINullablesSetToNull, 'reset_completed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reset_completed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reset_completed_at'] = $reset_completed_at;

        return $this;
    }

    /**
     * Gets node_deleted_at
     *
     * @return string|null
     */
    public function getNodeDeletedAt()
    {
        return $this->container['node_deleted_at'];
    }

    /**
     * Sets node_deleted_at
     *
     * @param string|null $node_deleted_at node_deleted_at
     *
     * @return self
     */
    public function setNodeDeletedAt($node_deleted_at)
    {
        if (is_null($node_deleted_at)) {
            array_push($this->openAPINullablesSetToNull, 'node_deleted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('node_deleted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['node_deleted_at'] = $node_deleted_at;

        return $this;
    }

    /**
     * Gets vm_deleted_at
     *
     * @return string|null
     */
    public function getVmDeletedAt()
    {
        return $this->container['vm_deleted_at'];
    }

    /**
     * Sets vm_deleted_at
     *
     * @param string|null $vm_deleted_at vm_deleted_at
     *
     * @return self
     */
    public function setVmDeletedAt($vm_deleted_at)
    {
        if (is_null($vm_deleted_at)) {
            array_push($this->openAPINullablesSetToNull, 'vm_deleted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('vm_deleted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['vm_deleted_at'] = $vm_deleted_at;

        return $this;
    }

    /**
     * Gets uncordoned_at
     *
     * @return string|null
     */
    public function getUncordonedAt()
    {
        return $this->container['uncordoned_at'];
    }

    /**
     * Sets uncordoned_at
     *
     * @param string|null $uncordoned_at uncordoned_at
     *
     * @return self
     */
    public function setUncordonedAt($uncordoned_at)
    {
        if (is_null($uncordoned_at)) {
            array_push($this->openAPINullablesSetToNull, 'uncordoned_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('uncordoned_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['uncordoned_at'] = $uncordoned_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


