<?php
/**
 * PublicInterface
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\\Sdk\Model;

use \ArrayAccess;
use \PidginHost\\Sdk\ObjectSerializer;

/**
 * PublicInterface Class Doc Comment
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PublicInterface implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PublicInterface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'interface' => 'string',
        'ipv4' => 'string',
        'ipv6' => 'string',
        'fw_rules_set' => 'string',
        'fw_policy_in' => '\PidginHost\\Sdk\Model\FwPolicyOutEnum',
        'fw_policy_out' => '\PidginHost\\Sdk\Model\FwPolicyOutEnum'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'interface' => null,
        'ipv4' => null,
        'ipv6' => null,
        'fw_rules_set' => null,
        'fw_policy_in' => null,
        'fw_policy_out' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'interface' => false,
        'ipv4' => false,
        'ipv6' => false,
        'fw_rules_set' => true,
        'fw_policy_in' => false,
        'fw_policy_out' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'interface' => 'interface',
        'ipv4' => 'ipv4',
        'ipv6' => 'ipv6',
        'fw_rules_set' => 'fw_rules_set',
        'fw_policy_in' => 'fw_policy_in',
        'fw_policy_out' => 'fw_policy_out'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'interface' => 'setInterface',
        'ipv4' => 'setIpv4',
        'ipv6' => 'setIpv6',
        'fw_rules_set' => 'setFwRulesSet',
        'fw_policy_in' => 'setFwPolicyIn',
        'fw_policy_out' => 'setFwPolicyOut'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'interface' => 'getInterface',
        'ipv4' => 'getIpv4',
        'ipv6' => 'getIpv6',
        'fw_rules_set' => 'getFwRulesSet',
        'fw_policy_in' => 'getFwPolicyIn',
        'fw_policy_out' => 'getFwPolicyOut'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('interface', $data ?? [], null);
        $this->setIfExists('ipv4', $data ?? [], null);
        $this->setIfExists('ipv6', $data ?? [], null);
        $this->setIfExists('fw_rules_set', $data ?? [], null);
        $this->setIfExists('fw_policy_in', $data ?? [], null);
        $this->setIfExists('fw_policy_out', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['interface'] === null) {
            $invalidProperties[] = "'interface' can't be null";
        }
        if ($this->container['ipv4'] === null) {
            $invalidProperties[] = "'ipv4' can't be null";
        }
        if ($this->container['ipv6'] === null) {
            $invalidProperties[] = "'ipv6' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets interface
     *
     * @return string
     */
    public function getInterface()
    {
        return $this->container['interface'];
    }

    /**
     * Sets interface
     *
     * @param string $interface interface
     *
     * @return self
     */
    public function setInterface($interface)
    {
        if (is_null($interface)) {
            throw new \InvalidArgumentException('non-nullable interface cannot be null');
        }
        $this->container['interface'] = $interface;

        return $this;
    }

    /**
     * Gets ipv4
     *
     * @return string
     */
    public function getIpv4()
    {
        return $this->container['ipv4'];
    }

    /**
     * Sets ipv4
     *
     * @param string $ipv4 ipv4
     *
     * @return self
     */
    public function setIpv4($ipv4)
    {
        if (is_null($ipv4)) {
            throw new \InvalidArgumentException('non-nullable ipv4 cannot be null');
        }
        $this->container['ipv4'] = $ipv4;

        return $this;
    }

    /**
     * Gets ipv6
     *
     * @return string
     */
    public function getIpv6()
    {
        return $this->container['ipv6'];
    }

    /**
     * Sets ipv6
     *
     * @param string $ipv6 ipv6
     *
     * @return self
     */
    public function setIpv6($ipv6)
    {
        if (is_null($ipv6)) {
            throw new \InvalidArgumentException('non-nullable ipv6 cannot be null');
        }
        $this->container['ipv6'] = $ipv6;

        return $this;
    }

    /**
     * Gets fw_rules_set
     *
     * @return string|null
     */
    public function getFwRulesSet()
    {
        return $this->container['fw_rules_set'];
    }

    /**
     * Sets fw_rules_set
     *
     * @param string|null $fw_rules_set ID or slug
     *
     * @return self
     */
    public function setFwRulesSet($fw_rules_set)
    {
        if (is_null($fw_rules_set)) {
            array_push($this->openAPINullablesSetToNull, 'fw_rules_set');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fw_rules_set', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fw_rules_set'] = $fw_rules_set;

        return $this;
    }

    /**
     * Gets fw_policy_in
     *
     * @return \PidginHost\\Sdk\Model\FwPolicyOutEnum|null
     */
    public function getFwPolicyIn()
    {
        return $this->container['fw_policy_in'];
    }

    /**
     * Sets fw_policy_in
     *
     * @param \PidginHost\\Sdk\Model\FwPolicyOutEnum|null $fw_policy_in fw_policy_in
     *
     * @return self
     */
    public function setFwPolicyIn($fw_policy_in)
    {
        if (is_null($fw_policy_in)) {
            throw new \InvalidArgumentException('non-nullable fw_policy_in cannot be null');
        }
        $this->container['fw_policy_in'] = $fw_policy_in;

        return $this;
    }

    /**
     * Gets fw_policy_out
     *
     * @return \PidginHost\\Sdk\Model\FwPolicyOutEnum|null
     */
    public function getFwPolicyOut()
    {
        return $this->container['fw_policy_out'];
    }

    /**
     * Sets fw_policy_out
     *
     * @param \PidginHost\\Sdk\Model\FwPolicyOutEnum|null $fw_policy_out fw_policy_out
     *
     * @return self
     */
    public function setFwPolicyOut($fw_policy_out)
    {
        if (is_null($fw_policy_out)) {
            throw new \InvalidArgumentException('non-nullable fw_policy_out cannot be null');
        }
        $this->container['fw_policy_out'] = $fw_policy_out;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


