<?php
/**
 * ScopeEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * ScopeEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;read_only&#x60; - Read only * &#x60;read_write&#x60; - Read &amp; Write
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScopeEnum
{
    /**
     * Possible values of this enum
     */
    public const READ_ONLY = 'read_only';

    public const READ_WRITE = 'read_write';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::READ_ONLY,
            self::READ_WRITE
        ];
    }
}


