<?php
/**
 * ServerDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\Sdk\Model;

use \ArrayAccess;
use \PidginHost\Sdk\ObjectSerializer;

/**
 * ServerDetail Class Doc Comment
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServerDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ServerDetail';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'hostname' => 'string',
        'project' => 'string',
        'image' => 'string',
        'package' => 'string',
        'cpus' => 'int',
        'memory' => 'int',
        'disk_size' => 'int',
        'generation' => 'string',
        'machine' => 'array<string,mixed>',
        'volumes' => '\PidginHost\Sdk\Model\Volume[]',
        'networks' => 'array<string,mixed>',
        'floating_ips' => '\PidginHost\Sdk\Model\FloatingIPSummary[]',
        'password' => 'string',
        'ssh_pub_key' => 'string',
        'status' => '\PidginHost\Sdk\Model\ResourceStatusEnum',
        'username' => 'string',
        'destroy_protection' => 'bool',
        'ha_enabled' => 'bool',
        'custom_os' => 'bool',
        'rescue_mode' => 'bool',
        'boot_iso' => 'string',
        'rescue_supported' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'hostname' => null,
        'project' => null,
        'image' => null,
        'package' => null,
        'cpus' => null,
        'memory' => null,
        'disk_size' => null,
        'generation' => null,
        'machine' => null,
        'volumes' => null,
        'networks' => null,
        'floating_ips' => null,
        'password' => null,
        'ssh_pub_key' => null,
        'status' => null,
        'username' => null,
        'destroy_protection' => null,
        'ha_enabled' => null,
        'custom_os' => null,
        'rescue_mode' => null,
        'boot_iso' => null,
        'rescue_supported' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'hostname' => false,
        'project' => false,
        'image' => false,
        'package' => false,
        'cpus' => false,
        'memory' => false,
        'disk_size' => false,
        'generation' => false,
        'machine' => false,
        'volumes' => false,
        'networks' => false,
        'floating_ips' => false,
        'password' => false,
        'ssh_pub_key' => false,
        'status' => false,
        'username' => false,
        'destroy_protection' => false,
        'ha_enabled' => false,
        'custom_os' => false,
        'rescue_mode' => false,
        'boot_iso' => true,
        'rescue_supported' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'hostname' => 'hostname',
        'project' => 'project',
        'image' => 'image',
        'package' => 'package',
        'cpus' => 'cpus',
        'memory' => 'memory',
        'disk_size' => 'disk_size',
        'generation' => 'generation',
        'machine' => 'machine',
        'volumes' => 'volumes',
        'networks' => 'networks',
        'floating_ips' => 'floating_ips',
        'password' => 'password',
        'ssh_pub_key' => 'ssh_pub_key',
        'status' => 'status',
        'username' => 'username',
        'destroy_protection' => 'destroy_protection',
        'ha_enabled' => 'ha_enabled',
        'custom_os' => 'custom_os',
        'rescue_mode' => 'rescue_mode',
        'boot_iso' => 'boot_iso',
        'rescue_supported' => 'rescue_supported'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'hostname' => 'setHostname',
        'project' => 'setProject',
        'image' => 'setImage',
        'package' => 'setPackage',
        'cpus' => 'setCpus',
        'memory' => 'setMemory',
        'disk_size' => 'setDiskSize',
        'generation' => 'setGeneration',
        'machine' => 'setMachine',
        'volumes' => 'setVolumes',
        'networks' => 'setNetworks',
        'floating_ips' => 'setFloatingIps',
        'password' => 'setPassword',
        'ssh_pub_key' => 'setSshPubKey',
        'status' => 'setStatus',
        'username' => 'setUsername',
        'destroy_protection' => 'setDestroyProtection',
        'ha_enabled' => 'setHaEnabled',
        'custom_os' => 'setCustomOs',
        'rescue_mode' => 'setRescueMode',
        'boot_iso' => 'setBootIso',
        'rescue_supported' => 'setRescueSupported'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'hostname' => 'getHostname',
        'project' => 'getProject',
        'image' => 'getImage',
        'package' => 'getPackage',
        'cpus' => 'getCpus',
        'memory' => 'getMemory',
        'disk_size' => 'getDiskSize',
        'generation' => 'getGeneration',
        'machine' => 'getMachine',
        'volumes' => 'getVolumes',
        'networks' => 'getNetworks',
        'floating_ips' => 'getFloatingIps',
        'password' => 'getPassword',
        'ssh_pub_key' => 'getSshPubKey',
        'status' => 'getStatus',
        'username' => 'getUsername',
        'destroy_protection' => 'getDestroyProtection',
        'ha_enabled' => 'getHaEnabled',
        'custom_os' => 'getCustomOs',
        'rescue_mode' => 'getRescueMode',
        'boot_iso' => 'getBootIso',
        'rescue_supported' => 'getRescueSupported'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('hostname', $data ?? [], null);
        $this->setIfExists('project', $data ?? [], null);
        $this->setIfExists('image', $data ?? [], null);
        $this->setIfExists('package', $data ?? [], null);
        $this->setIfExists('cpus', $data ?? [], null);
        $this->setIfExists('memory', $data ?? [], null);
        $this->setIfExists('disk_size', $data ?? [], null);
        $this->setIfExists('generation', $data ?? [], null);
        $this->setIfExists('machine', $data ?? [], null);
        $this->setIfExists('volumes', $data ?? [], null);
        $this->setIfExists('networks', $data ?? [], null);
        $this->setIfExists('floating_ips', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('ssh_pub_key', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('destroy_protection', $data ?? [], null);
        $this->setIfExists('ha_enabled', $data ?? [], null);
        $this->setIfExists('custom_os', $data ?? [], null);
        $this->setIfExists('rescue_mode', $data ?? [], null);
        $this->setIfExists('boot_iso', $data ?? [], null);
        $this->setIfExists('rescue_supported', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['hostname'] === null) {
            $invalidProperties[] = "'hostname' can't be null";
        }
        if (!is_null($this->container['project']) && (mb_strlen($this->container['project']) > 200)) {
            $invalidProperties[] = "invalid value for 'project', the character length must be smaller than or equal to 200.";
        }

        if ($this->container['image'] === null) {
            $invalidProperties[] = "'image' can't be null";
        }
        if ($this->container['package'] === null) {
            $invalidProperties[] = "'package' can't be null";
        }
        if ($this->container['cpus'] === null) {
            $invalidProperties[] = "'cpus' can't be null";
        }
        if ($this->container['memory'] === null) {
            $invalidProperties[] = "'memory' can't be null";
        }
        if ($this->container['disk_size'] === null) {
            $invalidProperties[] = "'disk_size' can't be null";
        }
        if ($this->container['generation'] === null) {
            $invalidProperties[] = "'generation' can't be null";
        }
        if ($this->container['machine'] === null) {
            $invalidProperties[] = "'machine' can't be null";
        }
        if ($this->container['volumes'] === null) {
            $invalidProperties[] = "'volumes' can't be null";
        }
        if ($this->container['networks'] === null) {
            $invalidProperties[] = "'networks' can't be null";
        }
        if ($this->container['floating_ips'] === null) {
            $invalidProperties[] = "'floating_ips' can't be null";
        }
        if (!is_null($this->container['password']) && (mb_strlen($this->container['password']) > 300)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be smaller than or equal to 300.";
        }

        if (!is_null($this->container['ssh_pub_key']) && (mb_strlen($this->container['ssh_pub_key']) > 3000)) {
            $invalidProperties[] = "invalid value for 'ssh_pub_key', the character length must be smaller than or equal to 3000.";
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['username'] === null) {
            $invalidProperties[] = "'username' can't be null";
        }
        if ($this->container['destroy_protection'] === null) {
            $invalidProperties[] = "'destroy_protection' can't be null";
        }
        if ($this->container['ha_enabled'] === null) {
            $invalidProperties[] = "'ha_enabled' can't be null";
        }
        if ($this->container['custom_os'] === null) {
            $invalidProperties[] = "'custom_os' can't be null";
        }
        if ($this->container['rescue_mode'] === null) {
            $invalidProperties[] = "'rescue_mode' can't be null";
        }
        if ($this->container['boot_iso'] === null && !$this->isNullableSetToNull('boot_iso')) {
            $invalidProperties[] = "'boot_iso' can't be null";
        }
        if ($this->container['rescue_supported'] === null) {
            $invalidProperties[] = "'rescue_supported' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets hostname
     *
     * @return string
     */
    public function getHostname()
    {
        return $this->container['hostname'];
    }

    /**
     * Sets hostname
     *
     * @param string $hostname hostname
     *
     * @return self
     */
    public function setHostname($hostname)
    {
        if (is_null($hostname)) {
            throw new \InvalidArgumentException('non-nullable hostname cannot be null');
        }
        $this->container['hostname'] = $hostname;

        return $this;
    }

    /**
     * Gets project
     *
     * @return string|null
     */
    public function getProject()
    {
        return $this->container['project'];
    }

    /**
     * Sets project
     *
     * @param string|null $project project
     *
     * @return self
     */
    public function setProject($project)
    {
        if (is_null($project)) {
            throw new \InvalidArgumentException('non-nullable project cannot be null');
        }
        if ((mb_strlen($project) > 200)) {
            throw new \InvalidArgumentException('invalid length for $project when calling ServerDetail., must be smaller than or equal to 200.');
        }

        $this->container['project'] = $project;

        return $this;
    }

    /**
     * Gets image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param string $image image
     *
     * @return self
     */
    public function setImage($image)
    {
        if (is_null($image)) {
            throw new \InvalidArgumentException('non-nullable image cannot be null');
        }
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets package
     *
     * @return string
     */
    public function getPackage()
    {
        return $this->container['package'];
    }

    /**
     * Sets package
     *
     * @param string $package package
     *
     * @return self
     */
    public function setPackage($package)
    {
        if (is_null($package)) {
            throw new \InvalidArgumentException('non-nullable package cannot be null');
        }
        $this->container['package'] = $package;

        return $this;
    }

    /**
     * Gets cpus
     *
     * @return int
     */
    public function getCpus()
    {
        return $this->container['cpus'];
    }

    /**
     * Sets cpus
     *
     * @param int $cpus cpus
     *
     * @return self
     */
    public function setCpus($cpus)
    {
        if (is_null($cpus)) {
            throw new \InvalidArgumentException('non-nullable cpus cannot be null');
        }
        $this->container['cpus'] = $cpus;

        return $this;
    }

    /**
     * Gets memory
     *
     * @return int
     */
    public function getMemory()
    {
        return $this->container['memory'];
    }

    /**
     * Sets memory
     *
     * @param int $memory memory
     *
     * @return self
     */
    public function setMemory($memory)
    {
        if (is_null($memory)) {
            throw new \InvalidArgumentException('non-nullable memory cannot be null');
        }
        $this->container['memory'] = $memory;

        return $this;
    }

    /**
     * Gets disk_size
     *
     * @return int
     */
    public function getDiskSize()
    {
        return $this->container['disk_size'];
    }

    /**
     * Sets disk_size
     *
     * @param int $disk_size disk_size
     *
     * @return self
     */
    public function setDiskSize($disk_size)
    {
        if (is_null($disk_size)) {
            throw new \InvalidArgumentException('non-nullable disk_size cannot be null');
        }
        $this->container['disk_size'] = $disk_size;

        return $this;
    }

    /**
     * Gets generation
     *
     * @return string
     */
    public function getGeneration()
    {
        return $this->container['generation'];
    }

    /**
     * Sets generation
     *
     * @param string $generation generation
     *
     * @return self
     */
    public function setGeneration($generation)
    {
        if (is_null($generation)) {
            throw new \InvalidArgumentException('non-nullable generation cannot be null');
        }
        $this->container['generation'] = $generation;

        return $this;
    }

    /**
     * Gets machine
     *
     * @return array<string,mixed>
     */
    public function getMachine()
    {
        return $this->container['machine'];
    }

    /**
     * Sets machine
     *
     * @param array<string,mixed> $machine machine
     *
     * @return self
     */
    public function setMachine($machine)
    {
        if (is_null($machine)) {
            throw new \InvalidArgumentException('non-nullable machine cannot be null');
        }
        $this->container['machine'] = $machine;

        return $this;
    }

    /**
     * Gets volumes
     *
     * @return \PidginHost\Sdk\Model\Volume[]
     */
    public function getVolumes()
    {
        return $this->container['volumes'];
    }

    /**
     * Sets volumes
     *
     * @param \PidginHost\Sdk\Model\Volume[] $volumes volumes
     *
     * @return self
     */
    public function setVolumes($volumes)
    {
        if (is_null($volumes)) {
            throw new \InvalidArgumentException('non-nullable volumes cannot be null');
        }
        $this->container['volumes'] = $volumes;

        return $this;
    }

    /**
     * Gets networks
     *
     * @return array<string,mixed>
     */
    public function getNetworks()
    {
        return $this->container['networks'];
    }

    /**
     * Sets networks
     *
     * @param array<string,mixed> $networks networks
     *
     * @return self
     */
    public function setNetworks($networks)
    {
        if (is_null($networks)) {
            throw new \InvalidArgumentException('non-nullable networks cannot be null');
        }
        $this->container['networks'] = $networks;

        return $this;
    }

    /**
     * Gets floating_ips
     *
     * @return \PidginHost\Sdk\Model\FloatingIPSummary[]
     */
    public function getFloatingIps()
    {
        return $this->container['floating_ips'];
    }

    /**
     * Sets floating_ips
     *
     * @param \PidginHost\Sdk\Model\FloatingIPSummary[] $floating_ips floating_ips
     *
     * @return self
     */
    public function setFloatingIps($floating_ips)
    {
        if (is_null($floating_ips)) {
            throw new \InvalidArgumentException('non-nullable floating_ips cannot be null');
        }
        $this->container['floating_ips'] = $floating_ips;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password password
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        if ((mb_strlen($password) > 300)) {
            throw new \InvalidArgumentException('invalid length for $password when calling ServerDetail., must be smaller than or equal to 300.');
        }

        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets ssh_pub_key
     *
     * @return string|null
     */
    public function getSshPubKey()
    {
        return $this->container['ssh_pub_key'];
    }

    /**
     * Sets ssh_pub_key
     *
     * @param string|null $ssh_pub_key Public key to apply for SSH login. Applying a non-empty key regenerates cloud-init and reboots a running server. Clearing removes the key from future cloud-init data, but does not revoke keys already in the guest.
     *
     * @return self
     */
    public function setSshPubKey($ssh_pub_key)
    {
        if (is_null($ssh_pub_key)) {
            throw new \InvalidArgumentException('non-nullable ssh_pub_key cannot be null');
        }
        if ((mb_strlen($ssh_pub_key) > 3000)) {
            throw new \InvalidArgumentException('invalid length for $ssh_pub_key when calling ServerDetail., must be smaller than or equal to 3000.');
        }

        $this->container['ssh_pub_key'] = $ssh_pub_key;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \PidginHost\Sdk\Model\ResourceStatusEnum
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \PidginHost\Sdk\Model\ResourceStatusEnum $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username username
     *
     * @return self
     */
    public function setUsername($username)
    {
        if (is_null($username)) {
            throw new \InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets destroy_protection
     *
     * @return bool
     */
    public function getDestroyProtection()
    {
        return $this->container['destroy_protection'];
    }

    /**
     * Sets destroy_protection
     *
     * @param bool $destroy_protection Prevents the server from being destroyed until disabled.
     *
     * @return self
     */
    public function setDestroyProtection($destroy_protection)
    {
        if (is_null($destroy_protection)) {
            throw new \InvalidArgumentException('non-nullable destroy_protection cannot be null');
        }
        $this->container['destroy_protection'] = $destroy_protection;

        return $this;
    }

    /**
     * Gets ha_enabled
     *
     * @return bool
     */
    public function getHaEnabled()
    {
        return $this->container['ha_enabled'];
    }

    /**
     * Sets ha_enabled
     *
     * @param bool $ha_enabled Enables Proxmox HA — automatic restart and migration on node failure.
     *
     * @return self
     */
    public function setHaEnabled($ha_enabled)
    {
        if (is_null($ha_enabled)) {
            throw new \InvalidArgumentException('non-nullable ha_enabled cannot be null');
        }
        $this->container['ha_enabled'] = $ha_enabled;

        return $this;
    }

    /**
     * Gets custom_os
     *
     * @return bool
     */
    public function getCustomOs()
    {
        return $this->container['custom_os'];
    }

    /**
     * Sets custom_os
     *
     * @param bool $custom_os Customer installed their own OS from an ISO; cloud-init features no longer apply
     *
     * @return self
     */
    public function setCustomOs($custom_os)
    {
        if (is_null($custom_os)) {
            throw new \InvalidArgumentException('non-nullable custom_os cannot be null');
        }
        $this->container['custom_os'] = $custom_os;

        return $this;
    }

    /**
     * Gets rescue_mode
     *
     * @return bool
     */
    public function getRescueMode()
    {
        return $this->container['rescue_mode'];
    }

    /**
     * Sets rescue_mode
     *
     * @param bool $rescue_mode rescue_mode
     *
     * @return self
     */
    public function setRescueMode($rescue_mode)
    {
        if (is_null($rescue_mode)) {
            throw new \InvalidArgumentException('non-nullable rescue_mode cannot be null');
        }
        $this->container['rescue_mode'] = $rescue_mode;

        return $this;
    }

    /**
     * Gets boot_iso
     *
     * @return string|null
     */
    public function getBootIso()
    {
        return $this->container['boot_iso'];
    }

    /**
     * Sets boot_iso
     *
     * @param string|null $boot_iso boot_iso
     *
     * @return self
     */
    public function setBootIso($boot_iso)
    {
        if (is_null($boot_iso)) {
            array_push($this->openAPINullablesSetToNull, 'boot_iso');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('boot_iso', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['boot_iso'] = $boot_iso;

        return $this;
    }

    /**
     * Gets rescue_supported
     *
     * @return bool
     */
    public function getRescueSupported()
    {
        return $this->container['rescue_supported'];
    }

    /**
     * Sets rescue_supported
     *
     * @param bool $rescue_supported rescue_supported
     *
     * @return self
     */
    public function setRescueSupported($rescue_supported)
    {
        if (is_null($rescue_supported)) {
            throw new \InvalidArgumentException('non-nullable rescue_supported cannot be null');
        }
        $this->container['rescue_supported'] = $rescue_supported;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


