<?php
/**
 * ServiceStatusEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\\Sdk\Model;
use \PidginHost\\Sdk\ObjectSerializer;

/**
 * ServiceStatusEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;pending&#x60; - Pending * &#x60;active&#x60; - Active * &#x60;provisioning&#x60; - Provisioning * &#x60;suspended&#x60; - Suspended * &#x60;terminated&#x60; - Terminated * &#x60;cancelled&#x60; - Cancelled * &#x60;postponed_cancellation&#x60; - Postponed cancellation * &#x60;action_pending&#x60; - Action pending
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceStatusEnum
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const ACTIVE = 'active';

    public const PROVISIONING = 'provisioning';

    public const SUSPENDED = 'suspended';

    public const TERMINATED = 'terminated';

    public const CANCELLED = 'cancelled';

    public const POSTPONED_CANCELLATION = 'postponed_cancellation';

    public const ACTION_PENDING = 'action_pending';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::ACTIVE,
            self::PROVISIONING,
            self::SUSPENDED,
            self::TERMINATED,
            self::CANCELLED,
            self::POSTPONED_CANCELLATION,
            self::ACTION_PENDING
        ];
    }
}


