<?php
/**
 * Status03cEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\\Sdk\Model;
use \PidginHost\\Sdk\ObjectSerializer;

/**
 * Status03cEnum Class Doc Comment
 *
 * @category Class
 * @description * &#x60;unpaid&#x60; - Unpaid * &#x60;paid&#x60; - Paid * &#x60;paid_with_funds&#x60; - Paid with funds * &#x60;overdue&#x60; - Overdue * &#x60;processing&#x60; - Processing * &#x60;cancelled&#x60; - Cancelled * &#x60;refunded&#x60; - Refunded
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Status03cEnum
{
    /**
     * Possible values of this enum
     */
    public const UNPAID = 'unpaid';

    public const PAID = 'paid';

    public const PAID_WITH_FUNDS = 'paid_with_funds';

    public const OVERDUE = 'overdue';

    public const PROCESSING = 'processing';

    public const CANCELLED = 'cancelled';

    public const REFUNDED = 'refunded';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNPAID,
            self::PAID,
            self::PAID_WITH_FUNDS,
            self::OVERDUE,
            self::PROCESSING,
            self::CANCELLED,
            self::REFUNDED
        ];
    }
}


