<?php
/**
 * TLD
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PidginHost\\Sdk\Model;

use \ArrayAccess;
use \PidginHost\\Sdk\ObjectSerializer;

/**
 * TLD Class Doc Comment
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TLD implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TLD';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'tld' => 'string',
        'price' => 'float',
        'renew_price' => 'float',
        'transfer_price' => 'float',
        'registrar' => 'string',
        'api_renewable' => 'bool',
        'idna_support' => 'bool',
        'wg_support' => 'bool',
        'reactivate_max_days' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'tld' => null,
        'price' => 'decimal',
        'renew_price' => 'decimal',
        'transfer_price' => 'decimal',
        'registrar' => null,
        'api_renewable' => null,
        'idna_support' => null,
        'wg_support' => null,
        'reactivate_max_days' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'tld' => false,
        'price' => false,
        'renew_price' => true,
        'transfer_price' => true,
        'registrar' => false,
        'api_renewable' => false,
        'idna_support' => false,
        'wg_support' => false,
        'reactivate_max_days' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'tld' => 'tld',
        'price' => 'price',
        'renew_price' => 'renew_price',
        'transfer_price' => 'transfer_price',
        'registrar' => 'registrar',
        'api_renewable' => 'api_renewable',
        'idna_support' => 'idna_support',
        'wg_support' => 'wg_support',
        'reactivate_max_days' => 'reactivate_max_days'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'tld' => 'setTld',
        'price' => 'setPrice',
        'renew_price' => 'setRenewPrice',
        'transfer_price' => 'setTransferPrice',
        'registrar' => 'setRegistrar',
        'api_renewable' => 'setApiRenewable',
        'idna_support' => 'setIdnaSupport',
        'wg_support' => 'setWgSupport',
        'reactivate_max_days' => 'setReactivateMaxDays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'tld' => 'getTld',
        'price' => 'getPrice',
        'renew_price' => 'getRenewPrice',
        'transfer_price' => 'getTransferPrice',
        'registrar' => 'getRegistrar',
        'api_renewable' => 'getApiRenewable',
        'idna_support' => 'getIdnaSupport',
        'wg_support' => 'getWgSupport',
        'reactivate_max_days' => 'getReactivateMaxDays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('tld', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('renew_price', $data ?? [], null);
        $this->setIfExists('transfer_price', $data ?? [], null);
        $this->setIfExists('registrar', $data ?? [], null);
        $this->setIfExists('api_renewable', $data ?? [], null);
        $this->setIfExists('idna_support', $data ?? [], null);
        $this->setIfExists('wg_support', $data ?? [], null);
        $this->setIfExists('reactivate_max_days', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['tld'] === null) {
            $invalidProperties[] = "'tld' can't be null";
        }
        if ((mb_strlen($this->container['tld']) > 200)) {
            $invalidProperties[] = "invalid value for 'tld', the character length must be smaller than or equal to 200.";
        }

        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if (!preg_match("/^-?\\d{0,8}(?:\\.\\d{0,2})?$/", $this->container['price'])) {
            $invalidProperties[] = "invalid value for 'price', must be conform to the pattern /^-?\\d{0,8}(?:\\.\\d{0,2})?$/.";
        }

        if (!is_null($this->container['renew_price']) && !preg_match("/^-?\\d{0,8}(?:\\.\\d{0,2})?$/", $this->container['renew_price'])) {
            $invalidProperties[] = "invalid value for 'renew_price', must be conform to the pattern /^-?\\d{0,8}(?:\\.\\d{0,2})?$/.";
        }

        if (!is_null($this->container['transfer_price']) && !preg_match("/^-?\\d{0,8}(?:\\.\\d{0,2})?$/", $this->container['transfer_price'])) {
            $invalidProperties[] = "invalid value for 'transfer_price', must be conform to the pattern /^-?\\d{0,8}(?:\\.\\d{0,2})?$/.";
        }

        if ($this->container['registrar'] === null) {
            $invalidProperties[] = "'registrar' can't be null";
        }
        if ((mb_strlen($this->container['registrar']) > 200)) {
            $invalidProperties[] = "invalid value for 'registrar', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['reactivate_max_days']) && ($this->container['reactivate_max_days'] > 32767)) {
            $invalidProperties[] = "invalid value for 'reactivate_max_days', must be smaller than or equal to 32767.";
        }

        if (!is_null($this->container['reactivate_max_days']) && ($this->container['reactivate_max_days'] < 0)) {
            $invalidProperties[] = "invalid value for 'reactivate_max_days', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets tld
     *
     * @return string
     */
    public function getTld()
    {
        return $this->container['tld'];
    }

    /**
     * Sets tld
     *
     * @param string $tld tld
     *
     * @return self
     */
    public function setTld($tld)
    {
        if (is_null($tld)) {
            throw new \InvalidArgumentException('non-nullable tld cannot be null');
        }
        if ((mb_strlen($tld) > 200)) {
            throw new \InvalidArgumentException('invalid length for $tld when calling TLD., must be smaller than or equal to 200.');
        }

        $this->container['tld'] = $tld;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param float $price Euro without TVA
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }

        if ((!preg_match("/^-?\\d{0,8}(?:\\.\\d{0,2})?$/", ObjectSerializer::toString($price)))) {
            throw new \InvalidArgumentException("invalid value for \$price when calling TLD., must conform to the pattern /^-?\\d{0,8}(?:\\.\\d{0,2})?$/.");
        }

        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets renew_price
     *
     * @return float|null
     */
    public function getRenewPrice()
    {
        return $this->container['renew_price'];
    }

    /**
     * Sets renew_price
     *
     * @param float|null $renew_price Euro without TVA
     *
     * @return self
     */
    public function setRenewPrice($renew_price)
    {
        if (is_null($renew_price)) {
            array_push($this->openAPINullablesSetToNull, 'renew_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('renew_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($renew_price) && (!preg_match("/^-?\\d{0,8}(?:\\.\\d{0,2})?$/", ObjectSerializer::toString($renew_price)))) {
            throw new \InvalidArgumentException("invalid value for \$renew_price when calling TLD., must conform to the pattern /^-?\\d{0,8}(?:\\.\\d{0,2})?$/.");
        }

        $this->container['renew_price'] = $renew_price;

        return $this;
    }

    /**
     * Gets transfer_price
     *
     * @return float|null
     */
    public function getTransferPrice()
    {
        return $this->container['transfer_price'];
    }

    /**
     * Sets transfer_price
     *
     * @param float|null $transfer_price Euro without TVA
     *
     * @return self
     */
    public function setTransferPrice($transfer_price)
    {
        if (is_null($transfer_price)) {
            array_push($this->openAPINullablesSetToNull, 'transfer_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transfer_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($transfer_price) && (!preg_match("/^-?\\d{0,8}(?:\\.\\d{0,2})?$/", ObjectSerializer::toString($transfer_price)))) {
            throw new \InvalidArgumentException("invalid value for \$transfer_price when calling TLD., must conform to the pattern /^-?\\d{0,8}(?:\\.\\d{0,2})?$/.");
        }

        $this->container['transfer_price'] = $transfer_price;

        return $this;
    }

    /**
     * Gets registrar
     *
     * @return string
     */
    public function getRegistrar()
    {
        return $this->container['registrar'];
    }

    /**
     * Sets registrar
     *
     * @param string $registrar registrar
     *
     * @return self
     */
    public function setRegistrar($registrar)
    {
        if (is_null($registrar)) {
            throw new \InvalidArgumentException('non-nullable registrar cannot be null');
        }
        if ((mb_strlen($registrar) > 200)) {
            throw new \InvalidArgumentException('invalid length for $registrar when calling TLD., must be smaller than or equal to 200.');
        }

        $this->container['registrar'] = $registrar;

        return $this;
    }

    /**
     * Gets api_renewable
     *
     * @return bool|null
     */
    public function getApiRenewable()
    {
        return $this->container['api_renewable'];
    }

    /**
     * Sets api_renewable
     *
     * @param bool|null $api_renewable api_renewable
     *
     * @return self
     */
    public function setApiRenewable($api_renewable)
    {
        if (is_null($api_renewable)) {
            throw new \InvalidArgumentException('non-nullable api_renewable cannot be null');
        }
        $this->container['api_renewable'] = $api_renewable;

        return $this;
    }

    /**
     * Gets idna_support
     *
     * @return bool|null
     */
    public function getIdnaSupport()
    {
        return $this->container['idna_support'];
    }

    /**
     * Sets idna_support
     *
     * @param bool|null $idna_support idna_support
     *
     * @return self
     */
    public function setIdnaSupport($idna_support)
    {
        if (is_null($idna_support)) {
            throw new \InvalidArgumentException('non-nullable idna_support cannot be null');
        }
        $this->container['idna_support'] = $idna_support;

        return $this;
    }

    /**
     * Gets wg_support
     *
     * @return bool|null
     */
    public function getWgSupport()
    {
        return $this->container['wg_support'];
    }

    /**
     * Sets wg_support
     *
     * @param bool|null $wg_support wg_support
     *
     * @return self
     */
    public function setWgSupport($wg_support)
    {
        if (is_null($wg_support)) {
            throw new \InvalidArgumentException('non-nullable wg_support cannot be null');
        }
        $this->container['wg_support'] = $wg_support;

        return $this;
    }

    /**
     * Gets reactivate_max_days
     *
     * @return int|null
     */
    public function getReactivateMaxDays()
    {
        return $this->container['reactivate_max_days'];
    }

    /**
     * Sets reactivate_max_days
     *
     * @param int|null $reactivate_max_days reactivate_max_days
     *
     * @return self
     */
    public function setReactivateMaxDays($reactivate_max_days)
    {
        if (is_null($reactivate_max_days)) {
            throw new \InvalidArgumentException('non-nullable reactivate_max_days cannot be null');
        }

        if (($reactivate_max_days > 32767)) {
            throw new \InvalidArgumentException('invalid value for $reactivate_max_days when calling TLD., must be smaller than or equal to 32767.');
        }
        if (($reactivate_max_days < 0)) {
            throw new \InvalidArgumentException('invalid value for $reactivate_max_days when calling TLD., must be bigger than or equal to 0.');
        }

        $this->container['reactivate_max_days'] = $reactivate_max_days;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


