<?php
/**
 * FeaturesEnumTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PidginHost\\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FeaturesEnumTest Class Doc Comment
 *
 * @category    Class
 * @description * &#x60;cert-manager&#x60; - Certificate manager * &#x60;ceph-csi&#x60; - Ceph CSI * &#x60;metrics-server&#x60; - Metrics Server * &#x60;cloudnative-pg&#x60; - CloudNative PG * &#x60;mariadb-operator&#x60; - MariaDB Operator
 * @package     PidginHost\\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FeaturesEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FeaturesEnum"
     */
    public function testFeaturesEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
