<?php
/**
 * BillingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PidginHost\Sdk\Test\Api;

use \PidginHost\Sdk\Configuration;
use \PidginHost\Sdk\ApiException;
use \PidginHost\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BillingApiTest Class Doc Comment
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BillingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for billingDepositsCreate
     *
     * .
     *
     */
    public function testBillingDepositsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingDepositsList
     *
     * .
     *
     */
    public function testBillingDepositsList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingDepositsRetrieve
     *
     * .
     *
     */
    public function testBillingDepositsRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingFundsList
     *
     * .
     *
     */
    public function testBillingFundsList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingFundsLogList
     *
     * .
     *
     */
    public function testBillingFundsLogList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingFundsNotificationSettingsCreate
     *
     * .
     *
     */
    public function testBillingFundsNotificationSettingsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingInvoicesList
     *
     * .
     *
     */
    public function testBillingInvoicesList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingInvoicesPayWithFundsCreate
     *
     * .
     *
     */
    public function testBillingInvoicesPayWithFundsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingInvoicesPdfRetrieve
     *
     * .
     *
     */
    public function testBillingInvoicesPdfRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingInvoicesRetrieve
     *
     * .
     *
     */
    public function testBillingInvoicesRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingServicesCancelCreate
     *
     * .
     *
     */
    public function testBillingServicesCancelCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingServicesChangeBillingCycleCreate
     *
     * .
     *
     */
    public function testBillingServicesChangeBillingCycleCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingServicesChangeCompanyCreate
     *
     * .
     *
     */
    public function testBillingServicesChangeCompanyCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingServicesList
     *
     * .
     *
     */
    public function testBillingServicesList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingServicesRetrieve
     *
     * .
     *
     */
    public function testBillingServicesRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingServicesToggleAutoPaymentCreate
     *
     * .
     *
     */
    public function testBillingServicesToggleAutoPaymentCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingSubscriptionsList
     *
     * .
     *
     */
    public function testBillingSubscriptionsList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for billingSubscriptionsRetrieve
     *
     * .
     *
     */
    public function testBillingSubscriptionsRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
