<?php
/**
 * DomainApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PidginHost\Sdk\Test\Api;

use \PidginHost\Sdk\Configuration;
use \PidginHost\Sdk\ApiException;
use \PidginHost\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DomainApiTest Class Doc Comment
 *
 * @category Class
 * @package  PidginHost\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DomainApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for domainDomainCancelCreate
     *
     * .
     *
     */
    public function testDomainDomainCancelCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainCheckAvailabilityCreate
     *
     * .
     *
     */
    public function testDomainDomainCheckAvailabilityCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainContactsCreate
     *
     * .
     *
     */
    public function testDomainDomainContactsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainCreate
     *
     * .
     *
     */
    public function testDomainDomainCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainList
     *
     * .
     *
     */
    public function testDomainDomainList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainNameserversCreate
     *
     * .
     *
     */
    public function testDomainDomainNameserversCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainPartialUpdate
     *
     * .
     *
     */
    public function testDomainDomainPartialUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainRenewCreate
     *
     * .
     *
     */
    public function testDomainDomainRenewCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainRetrieve
     *
     * .
     *
     */
    public function testDomainDomainRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainTransferRoDomainCreate
     *
     * .
     *
     */
    public function testDomainDomainTransferRoDomainCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainDomainUpdate
     *
     * .
     *
     */
    public function testDomainDomainUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainRegistrantsCreate
     *
     * .
     *
     */
    public function testDomainRegistrantsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainRegistrantsDestroy
     *
     * .
     *
     */
    public function testDomainRegistrantsDestroy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainRegistrantsList
     *
     * .
     *
     */
    public function testDomainRegistrantsList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainRegistrantsPartialUpdate
     *
     * .
     *
     */
    public function testDomainRegistrantsPartialUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainRegistrantsRetrieve
     *
     * .
     *
     */
    public function testDomainRegistrantsRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainRegistrantsUpdate
     *
     * .
     *
     */
    public function testDomainRegistrantsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainTldList
     *
     * .
     *
     */
    public function testDomainTldList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for domainTldRetrieve
     *
     * .
     *
     */
    public function testDomainTldRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
