<?php
/**
 * HostingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PidginHost\\Sdk\Test\Api;

use \PidginHost\\Sdk\Configuration;
use \PidginHost\\Sdk\ApiException;
use \PidginHost\\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HostingApiTest Class Doc Comment
 *
 * @category Class
 * @package  PidginHost\\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HostingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for hostingHostingChangePasswordCreate
     *
     * .
     *
     */
    public function testHostingHostingChangePasswordCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for hostingHostingList
     *
     * .
     *
     */
    public function testHostingHostingList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for hostingHostingRetrieve
     *
     * .
     *
     */
    public function testHostingHostingRetrieve()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
